# Generated by Django 4.2.13 on 2026-05-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_channels', to='chat.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='channel',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('text', 'Tekstowy'), ('voice', 'Głosowy')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('name', 'parent')},
        ),
    ]
